export interface SymbolEntry {
  id: string;
  name: string;
  glyph?: string;
  category: "celestial" | "zodiac" | "house" | "aspect" | "element" | "karmic" | "decorative";
  neonColor: string;
  shadowClass: string;
  perchancePrompt: string;
  usedIn: string;
  imagePath: string;
}

const BP = "digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges";

const SYMBOLS: SymbolEntry[] = [
  { id: "sun", name: "Sun", glyph: "☉", category: "celestial", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `luminous golden sun corona flares radiating through dark space, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "Chart center, Leo, core identity", imagePath: "/images/symbols/sun.webp" },
  { id: "moon", name: "Moon", glyph: "☽", category: "celestial", neonColor: "#C0C0FF", shadowClass: "shadow-neon-gold", perchancePrompt: `silver crescent moon liquid mercury surface crater glow, moonlit tide, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "Cancer, 4th, emotions", imagePath: "/images/symbols/moon.webp" },
  { id: "mercury", name: "Mercury", glyph: "☿", category: "celestial", neonColor: "#00E5FF", shadowClass: "shadow-neon-cyan", perchancePrompt: `winged caduceus staff electric blue neon, quicksilver fluidity, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "3rd/6th, communication", imagePath: "/images/symbols/mercury.webp" },
  { id: "venus", name: "Venus", glyph: "♀", category: "celestial", neonColor: "#FF69B4", shadowClass: "shadow-neon-magenta", perchancePrompt: `rose-gold celestial mirror pearl luminescence, divine feminine, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "2nd/7th, love, beauty", imagePath: "/images/symbols/venus.webp" },
  { id: "mars", name: "Mars", glyph: "♂", category: "celestial", neonColor: "#FF2D2D", shadowClass: "shadow-neon-gold", perchancePrompt: `crimson war shield plasma arcs, warrior spirit, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "1st house, drive", imagePath: "/images/symbols/mars.webp" },
  { id: "jupiter", name: "Jupiter", glyph: "♃", category: "celestial", neonColor: "#FFB347", shadowClass: "shadow-neon-gold", perchancePrompt: `amber lightning bolt expanding golden rings, sage wisdom, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "9th house, luck", imagePath: "/images/symbols/jupiter.webp" },
  { id: "saturn", name: "Saturn", glyph: "♄", category: "celestial", neonColor: "#404040", shadowClass: "shadow-neon-gold", perchancePrompt: `obsidian scythe dark amber ring restraints, lord of karma, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "10th house, time", imagePath: "/images/symbols/saturn.webp" },
  { id: "uranus", name: "Uranus", glyph: "♅", category: "celestial", neonColor: "#00BFFF", shadowClass: "shadow-neon-cyan", perchancePrompt: `electric blue lightning shattering crystal, awakening, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "11th, rebellion", imagePath: "/images/symbols/uranus.webp" },
  { id: "neptune", name: "Neptune", glyph: "♆", category: "celestial", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `deep violet trident dissolving misty ocean, mystical veil, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "12th, mysticism", imagePath: "/images/symbols/neptune.webp" },
  { id: "pluto", name: "Pluto", glyph: "♇", category: "celestial", neonColor: "#FF00FF", shadowClass: "shadow-neon-magenta", perchancePrompt: `obsidian phoenix rising volcanic ember underglow, underworld, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "8th, transformation", imagePath: "/images/symbols/pluto.webp" },
  { id: "north-node", name: "North Node", glyph: "☊", category: "celestial", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `golden dragon head upward spiral staircase stars, soul destiny, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "Karmic path", imagePath: "/images/symbols/north-node.webp" },
  { id: "south-node", name: "South Node", glyph: "☋", category: "celestial", neonColor: "#C0C0FF", shadowClass: "shadow-neon-gold", perchancePrompt: `silver dragon tail descending roots ancient earth, past life, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "Past life", imagePath: "/images/symbols/south-node.webp" },
  { id: "chiron", name: "Chiron", glyph: "⚷", category: "celestial", neonColor: "#98FF98", shadowClass: "shadow-neon-gold", perchancePrompt: `broken key mending itself teal healing light, wounded healer, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "Core wound, healing", imagePath: "/images/symbols/chiron.webp" },
  { id: "lilith", name: "Lilith", glyph: "⚸", category: "celestial", neonColor: "#FF00FF", shadowClass: "shadow-neon-magenta", perchancePrompt: `inverted black crescent moon shadow serpent, dark feminine, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "Shadow self", imagePath: "/images/symbols/lilith.webp" },
  { id: "ascendant", name: "Ascendant", category: "celestial", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `horizon line golden dawn light cracking darkness, rising sun, digital painting style, dark galaxy nebula background, celestial nightclub aesthetic, ethereal mystical atmosphere, high contrast, rim lighting, cosmic dust particles, 8k detailed, deep space void, neon glow edges`, usedIn: "1st cusp, persona", imagePath: "/images/symbols/ascendant.webp" },
  { id: "aries", name: "Aries", glyph: "♈", category: "zodiac", neonColor: "#FF2D2D", shadowClass: "shadow-neon-gold", perchancePrompt: `majestic ram curved horns wreathed wildfire forge sparks, ${BP}`, usedIn: "Aries placements", imagePath: "/images/symbols/aries.webp" },
  { id: "taurus", name: "Taurus", glyph: "♉", category: "zodiac", neonColor: "#00FF88", shadowClass: "shadow-neon-gold", perchancePrompt: `powerful bull emerald garden granite monolith, abundance, ${BP}`, usedIn: "Taurus placements", imagePath: "/images/symbols/taurus.webp" },
  { id: "gemini", name: "Gemini", glyph: "♊", category: "zodiac", neonColor: "#00E5FF", shadowClass: "shadow-neon-cyan", perchancePrompt: `twin silhouettes mirror winged sandals, duality, ${BP}`, usedIn: "Gemini placements", imagePath: "/images/symbols/gemini.webp" },
  { id: "cancer", name: "Cancer", glyph: "♋", category: "zodiac", neonColor: "#C0C0FF", shadowClass: "shadow-neon-gold", perchancePrompt: `crab moonlit tide pool glowing pearl shell, nurturing, ${BP}`, usedIn: "Cancer placements", imagePath: "/images/symbols/cancer.webp" },
  { id: "leo", name: "Leo", glyph: "♌", category: "zodiac", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `regal lion flowing mane solar disc throne stars, royal, ${BP}`, usedIn: "Leo placements", imagePath: "/images/symbols/leo.webp" },
  { id: "virgo", name: "Virgo", glyph: "♍", category: "zodiac", neonColor: "#98FF98", shadowClass: "shadow-neon-gold", perchancePrompt: `sheaf wheat crystalline lattice ancient scroll, precision, ${BP}`, usedIn: "Virgo placements", imagePath: "/images/symbols/virgo.webp" },
  { id: "libra", name: "Libra", glyph: "♎", category: "zodiac", neonColor: "#FF69B4", shadowClass: "shadow-neon-magenta", perchancePrompt: `golden scales justice floating dove feather, harmony, ${BP}`, usedIn: "Libra placements", imagePath: "/images/symbols/libra.webp" },
  { id: "scorpio", name: "Scorpio", glyph: "♏", category: "zodiac", neonColor: "#FF00FF", shadowClass: "shadow-neon-magenta", perchancePrompt: `scorpion transforming phoenix deep water vortex, alchemy, ${BP}`, usedIn: "Scorpio placements", imagePath: "/images/symbols/scorpio.webp" },
  { id: "sagittarius", name: "Sagittarius", glyph: "♐", category: "zodiac", neonColor: "#FFB347", shadowClass: "shadow-neon-gold", perchancePrompt: `centaur archer arrow flight distant galaxy, seeker truth, ${BP}`, usedIn: "Sagittarius placements", imagePath: "/images/symbols/sagittarius.webp" },
  { id: "capricorn", name: "Capricorn", glyph: "♑", category: "zodiac", neonColor: "#404040", shadowClass: "shadow-neon-gold", perchancePrompt: `sea-goat climbing obsidian mountain peak hourglass, ambition, ${BP}`, usedIn: "Capricorn placements", imagePath: "/images/symbols/capricorn.webp" },
  { id: "aquarius", name: "Aquarius", glyph: "♒", category: "zodiac", neonColor: "#00BFFF", shadowClass: "shadow-neon-cyan", perchancePrompt: `water bearer pouring stars circuit board constellation, future, ${BP}`, usedIn: "Aquarius placements", imagePath: "/images/symbols/aquarius.webp" },
  { id: "pisces", name: "Pisces", glyph: "♓", category: "zodiac", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `two fish swimming cosmic nebula veil between worlds, ${BP}`, usedIn: "Pisces placements", imagePath: "/images/symbols/pisces.webp" },
  { id: "house-1", name: "House of Self", category: "house", neonColor: "#FF2D2D", shadowClass: "shadow-neon-gold", perchancePrompt: `neon mirror reflecting dawn horizon theatrical mask, identity, ${BP}`, usedIn: "1st house", imagePath: "/images/symbols/house-1.webp" },
  { id: "house-2", name: "House of Value", category: "house", neonColor: "#00FF88", shadowClass: "shadow-neon-gold", perchancePrompt: `ancient treasure vault roots growing gold coins earth, security, ${BP}`, usedIn: "2nd house", imagePath: "/images/symbols/house-2.webp" },
  { id: "house-3", name: "House of Communication", category: "house", neonColor: "#00E5FF", shadowClass: "shadow-neon-cyan", perchancePrompt: `neon quill writing winged scrolls constellation pathways, ${BP}`, usedIn: "3rd house", imagePath: "/images/symbols/house-3.webp" },
  { id: "house-4", name: "House of Home", category: "house", neonColor: "#C0C0FF", shadowClass: "shadow-neon-gold", perchancePrompt: `moonlit roots underground ancestral tree hearth fire, soul home, ${BP}`, usedIn: "4th house", imagePath: "/images/symbols/house-4.webp" },
  { id: "house-5", name: "House of Pleasure", category: "house", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `spotlit stage heartburst constellation golden chalice, joy, ${BP}`, usedIn: "5th house", imagePath: "/images/symbols/house-5.webp" },
  { id: "house-6", name: "House of Health", category: "house", neonColor: "#98FF98", shadowClass: "shadow-neon-gold", perchancePrompt: `glowing crystalline body labyrinth wheat clock gears, service, ${BP}`, usedIn: "6th house", imagePath: "/images/symbols/house-6.webp" },
  { id: "house-7", name: "House of Partnership", category: "house", neonColor: "#FF69B4", shadowClass: "shadow-neon-magenta", perchancePrompt: `two hands reaching mirrored reflections wedding band nebula, union, ${BP}`, usedIn: "7th house", imagePath: "/images/symbols/house-7.webp" },
  { id: "house-8", name: "House of Transformation", category: "house", neonColor: "#FF00FF", shadowClass: "shadow-neon-magenta", perchancePrompt: `phoenix rising obsidian chrysalis dark water alchemical crucible, ${BP}`, usedIn: "8th house", imagePath: "/images/symbols/house-8.webp" },
  { id: "house-9", name: "House of Philosophy", category: "house", neonColor: "#FFB347", shadowClass: "shadow-neon-gold", perchancePrompt: `spiral galaxy road mountaintop beacon compass rose, wisdom, ${BP}`, usedIn: "9th house", imagePath: "/images/symbols/house-9.webp" },
  { id: "house-10", name: "House of Legacy", category: "house", neonColor: "#404040", shadowClass: "shadow-neon-gold", perchancePrompt: `midnight throne zenith point crown constellation, legacy, ${BP}`, usedIn: "10th house", imagePath: "/images/symbols/house-10.webp" },
  { id: "house-11", name: "House of Community", category: "house", neonColor: "#00BFFF", shadowClass: "shadow-neon-cyan", perchancePrompt: `constellation network electric bees star-web, collective, ${BP}`, usedIn: "11th house", imagePath: "/images/symbols/house-11.webp" },
  { id: "house-12", name: "House of the Unconscious", category: "house", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `deep ocean abyss dissolving veil cosmic whale dream realm, ${BP}`, usedIn: "12th house", imagePath: "/images/symbols/house-12.webp" },
  { id: "conjunction", name: "Conjunction", category: "aspect", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `two neon circles merging single unified golden glow, fusion, ${BP}`, usedIn: "Conjunction aspects", imagePath: "/images/symbols/conjunction.webp" },
  { id: "sextile", name: "Sextile", category: "aspect", neonColor: "#00FF88", shadowClass: "shadow-neon-gold", perchancePrompt: `six-pointed star gentle arc bridging luminous planets, opportunity, ${BP}`, usedIn: "Sextile aspects", imagePath: "/images/symbols/sextile.webp" },
  { id: "square", name: "Square", category: "aspect", neonColor: "#FF2D2D", shadowClass: "shadow-neon-gold", perchancePrompt: `fractured diamond tension lines neon prison bars, challenge, ${BP}`, usedIn: "Square aspects", imagePath: "/images/symbols/square.webp" },
  { id: "trine", name: "Trine", category: "aspect", neonColor: "#00BFFF", shadowClass: "shadow-neon-cyan", perchancePrompt: `perfect luminous triangle flowing river starlight, harmony, ${BP}`, usedIn: "Trine aspects", imagePath: "/images/symbols/trine.webp" },
  { id: "opposition", name: "Opposition", category: "aspect", neonColor: "#FF00FF", shadowClass: "shadow-neon-magenta", perchancePrompt: `cosmic teeter-totter axis two worlds pulling apart twilight, polarity, ${BP}`, usedIn: "Opposition aspects", imagePath: "/images/symbols/opposition.webp" },
  { id: "quincunx", name: "Quincunx", category: "aspect", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `zigzag bridge misaligned gears trying mesh, awkward adjustment, ${BP}`, usedIn: "Quincunx aspects", imagePath: "/images/symbols/quincunx.webp" },
  { id: "fire", name: "Fire", category: "element", neonColor: "#FF2D2D", shadowClass: "shadow-neon-gold", perchancePrompt: `spiral flame phoenix wing magma veins, elemental fire, ${BP}`, usedIn: "Fire signs", imagePath: "/images/symbols/fire.webp" },
  { id: "earth", name: "Earth", category: "element", neonColor: "#00FF88", shadowClass: "shadow-neon-gold", perchancePrompt: `glowing root system crystalline cave gemstones, elemental earth, ${BP}`, usedIn: "Earth signs", imagePath: "/images/symbols/earth.webp" },
  { id: "air", name: "Air", category: "element", neonColor: "#00E5FF", shadowClass: "shadow-neon-cyan", perchancePrompt: `single feather silver wind storm cloud lightning, elemental air, ${BP}`, usedIn: "Air signs", imagePath: "/images/symbols/air.webp" },
  { id: "water", name: "Water", category: "element", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `bioluminescent deep ocean wave moon-tide tears stars, elemental water, ${BP}`, usedIn: "Water signs", imagePath: "/images/symbols/water.webp" },
  { id: "ether", name: "Ether", category: "element", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `nebula spiral cosmic web, fifth element pure spirit, ${BP}`, usedIn: "Spirit", imagePath: "/images/symbols/ether.webp" },
  { id: "butterfly", name: "Butterfly", category: "karmic", neonColor: "#FF00FF", shadowClass: "shadow-neon-magenta", perchancePrompt: `neon-winged butterfly emerging dark chrysalis, metamorphosis, ${BP}`, usedIn: "Transformation", imagePath: "/images/symbols/butterfly.webp" },
  { id: "anchor", name: "Anchor", category: "karmic", neonColor: "#C0C0FF", shadowClass: "shadow-neon-gold", perchancePrompt: `glowing silver anchor sinking cosmic sea chain dissolving stardust, grounding, ${BP}`, usedIn: "Stability", imagePath: "/images/symbols/anchor.webp" },
  { id: "phoenix", name: "Phoenix", category: "karmic", neonColor: "#FF00FF", shadowClass: "shadow-neon-magenta", perchancePrompt: `magnificent firebird rising obsidian ash wings flame, rebirth, ${BP}`, usedIn: "Rebirth, 8th", imagePath: "/images/symbols/phoenix.webp" },
  { id: "ouroboros", name: "Ouroboros", category: "karmic", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `serpent eating own tail infinity loop neon gold, eternal cycle, ${BP}`, usedIn: "Cycles, karma", imagePath: "/images/symbols/ouroboros.webp" },
  { id: "lotus", name: "Lotus", category: "karmic", neonColor: "#FF69B4", shadowClass: "shadow-neon-magenta", perchancePrompt: `lotus blooming black cosmic water petals violet-pink, enlightenment, ${BP}`, usedIn: "Awakening", imagePath: "/images/symbols/lotus.webp" },
  { id: "key", name: "Key of Destiny", category: "karmic", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `ornate skeleton key unlocking constellation door deep space, ${BP}`, usedIn: "Destiny", imagePath: "/images/symbols/key.webp" },
  { id: "labyrinth", name: "Labyrinth", category: "karmic", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `neon maze spiraling inward central glowing star, life journey, ${BP}`, usedIn: "Life path", imagePath: "/images/symbols/labyrinth.webp" },
  { id: "thread-of-fate", name: "Thread of Fate", category: "karmic", neonColor: "#C0C0FF", shadowClass: "shadow-neon-gold", perchancePrompt: `three silver threads weaving intricate tapestry dark space, Moirai, ${BP}`, usedIn: "Fate", imagePath: "/images/symbols/thread-of-fate.webp" },
  { id: "tree-of-life", name: "Tree of Life", category: "karmic", neonColor: "#00FF88", shadowClass: "shadow-neon-gold", perchancePrompt: `cosmic tree roots galaxy branches constellations, growth, ${BP}`, usedIn: "Growth, ancestry", imagePath: "/images/symbols/tree-of-life.webp" },
  { id: "hourglass", name: "Hourglass", category: "karmic", neonColor: "#404040", shadowClass: "shadow-neon-gold", perchancePrompt: `glass hourglass falling star-sand onyx frame, Saturn time, ${BP}`, usedIn: "Time, Saturn", imagePath: "/images/symbols/hourglass.webp" },
  { id: "eclipse", name: "Eclipse", category: "karmic", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `black sun corona lunar shadow passing, cosmic destiny, ${BP}`, usedIn: "Eclipse destiny", imagePath: "/images/symbols/eclipse.webp" },
  { id: "vesica-piscis", name: "Vesica Pisces", category: "karmic", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `sacred geometry vesica piscis portal between worlds, divine, ${BP}`, usedIn: "Sacred geometry", imagePath: "/images/symbols/vesica-piscis.webp" },
  { id: "seed", name: "Cosmic Seed", category: "karmic", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `glowing golden seed cracking open void potential energy, beginnings, ${BP}`, usedIn: "New beginnings", imagePath: "/images/symbols/seed.webp" },
  { id: "compass", name: "Compass", category: "karmic", neonColor: "#FFB347", shadowClass: "shadow-neon-gold", perchancePrompt: `floating celestial compass needle pointing North Star galaxy, direction, ${BP}`, usedIn: "Direction, purpose", imagePath: "/images/symbols/compass.webp" },
  { id: "galaxy-bg", name: "Galaxy Background", category: "decorative", neonColor: "#0A0A1A", shadowClass: "", perchancePrompt: `deep space galaxy purple indigo nebula scattered neon stars, vast void, ${BP}`, usedIn: "Fullscreen bg", imagePath: "/images/symbols/galaxy-bg.webp" },
  { id: "starfield", name: "Starfield", category: "decorative", neonColor: "#C0C0FF", shadowClass: "", perchancePrompt: `subtle twinkling starfield pattern tiny luminous dots void, minimal, ${BP}`, usedIn: "Card texture", imagePath: "/images/symbols/starfield.webp" },
  { id: "neon-ring", name: "Neon Ring", category: "decorative", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `perfect circular neon ring glowing dark space, chart border, ${BP}`, usedIn: "Chart border", imagePath: "/images/symbols/neon-ring.webp" },
  { id: "constellation-lines", name: "Constellation Lines", category: "decorative", neonColor: "#00BFFF", shadowClass: "shadow-neon-cyan", perchancePrompt: `thin luminous constellation lines connecting bright stars geometric web, ${BP}`, usedIn: "Chart edges", imagePath: "/images/symbols/constellation-lines.webp" },
  { id: "zenith-glyph", name: "Midheaven MC", category: "decorative", neonColor: "#FFD700", shadowClass: "shadow-neon-gold", perchancePrompt: `glowing glyph zenith point vertical beam light, pinnacle, ${BP}`, usedIn: "MC marker", imagePath: "/images/symbols/zenith-glyph.webp" },
  { id: "nadir-glyph", name: "Imum Coeli IC", category: "decorative", neonColor: "#C0C0FF", shadowClass: "shadow-neon-gold", perchancePrompt: `inverted glowing glyph nadir point roots descending, foundation, ${BP}`, usedIn: "IC marker", imagePath: "/images/symbols/nadir-glyph.webp" },
  { id: "divider", name: "Section Divider", category: "decorative", neonColor: "#8B00FF", shadowClass: "shadow-neon-purple", perchancePrompt: `horizontal neon line embedded planetary glyphs, cosmic divider, ${BP}`, usedIn: "Section dividers", imagePath: "/images/symbols/divider.webp" },
];

export default SYMBOLS;
export function getSymbol(id: string) { return SYMBOLS.find(s => s.id === id); }
export function getByCategory(c: SymbolEntry["category"]) { return SYMBOLS.filter(s => s.category === c); }
export function getAllIds() { return SYMBOLS.map(s => s.id); }
export const TOTAL = SYMBOLS.length;
